server:
  port: 8001
  servlet:
    context-path: /spring-graphql-query-vs-rest-get-method

graphql:
  extended-scalars: BigDecimal, Date

spring:

  graphql:
    path: /customers-graphql
    schema:
      printer:
        enabled: true # The GraphQL schema can be viewed at HTTP GET /graphql/schema by enabling this property ???
      locations: classpath:graphql/

  datasource:
    url: jdbc:h2:mem:customerdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect



# Used for test, it logs queries
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
              MongoTemplate: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
